### PR TITLE
the report method its only triggered on production mode

### PR DESCRIPTION
**Pull request by mateosilguero**
, otherwise, the api will generate (useless) data while the app is being developed

### CODE REVIEW

**Comment by Hermanya** [comment]
I made some changes, primarily switched to `process.env.NODE_ENV !== 'production'` based on https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

@mateosilguero makes sense?

**Comment by mateosilguero** [comment]
totally. this a cleanest solution.

**Comment by Hermanya** [comment]
Thanks man, let me know if you have any other ideas 🙂

**Comment by Hermanya** [comment]
v1.1.0 is up

**Comment by mateosilguero** [comment]
Awesome !

**Pull request merged**
