### PR TITLE
variants invocations rate can be controlled by weights

### PR DESCRIPTION
**Pull request by mateosilguero**
Using weights, variants invocations rates can be 50/50, or 30/70, or 50/30/20.

### CODE REVIEW

**Comment by Hermanya** [comment]
Interesting, I will take a look after work!

**Comment by Hermanya** [comment]
I pushed some potential improvements, @mateosilguero let me know what you think.

**Comment by mateosilguero** [comment]
I like it ! it's simplified approach.

**Comment by Hermanya** [comment]
v1.2.0 is out

**Pull request merged**
